import { Horse } from './types';

// Foto del Nivel Avanzado GP (Imperioso GL) usada como placeholder de alta calidad
const BROWN_HORSE_IMG = 'https://images.unsplash.com/photo-1598974357801-cbca100e65d3?q=80&w=2574&auto=format&fit=crop';

const GALLERY_IMGS = [
  'https://images.unsplash.com/photo-1548094967-e25a127d1f6d?q=80&w=2568&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1534008902787-0b62d398b713?q=80&w=2574&auto=format&fit=crop',
  'https://images.unsplash.com/photo-1629814674640-52e69736db89?q=80&w=2670&auto=format&fit=crop'
];

export const HORSES: Horse[] = [
  // --- DOMA CLÁSICA ---
  {
    id: 'imperioso-gl',
    name: 'IMPERIOSO GL',
    category: 'doma',
    level: 'alto',
    age: 8,
    gender: 'Stallion',
    breed: 'KWPN',
    country: 'Holanda',
    height: '1.74 m',
    coat: 'Tordo',
    price: 85000,
    description: 'Presentamos a un semental KWPN de excepcional presencia. Imperioso GL combina una morfología moderna con una mente cooperativa. Sus movimientos son elásticos, con una suspensión natural en el trote y un galope cuesta arriba. Confirmado en nivel San Jorge.',
    lineage: 'Totilas x Donnerhall',
    image: BROWN_HORSE_IMG, // Usamos la misma constante ya que es la foto original
    gallery: GALLERY_IMGS,
    features: ['Nivel San Jorge', 'Apto Reproductor'],
    video: 'https://www.youtube.com/embed/sample',
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },
  {
    id: 'donatello-noir',
    name: 'DONATELLO NOIR',
    category: 'doma',
    level: 'alto',
    age: 10,
    gender: 'Gelding',
    breed: 'Oldenburgo',
    country: 'Alemania',
    height: '1.72 m',
    coat: 'Castaño',
    price: 95000,
    description: 'Un maestro de la pista. Donatello es un caballo profesor, ideal para juveniles que quieran competir en campeonatos europeos. Cambios de pie a dos trancos confirmados, piruetas canter muy centradas y un carácter a prueba de bombas.',
    lineage: 'De Niro x Sandro Hit',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Intermedia I', 'Piruetas Confirmadas'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },
  {
    id: 'faraon-negro',
    name: 'FARAÓN NOIR',
    category: 'doma',
    level: 'medio',
    age: 6,
    gender: 'Gelding',
    breed: 'Hannoveriano',
    country: 'Alemania',
    height: '1.72 m',
    coat: 'Negro',
    price: 65000,
    description: 'La elegancia personificada. Tres aires de calidad superior con un galope cuesta arriba impresionante. Finalista en campeonatos nacionales de caballos jóvenes. Ideal para un jinete ambicioso que busque calidad para el futuro.',
    lineage: 'Negro x Jazz',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Campeón 6 Años', 'Potencial GP']
  },
  {
    id: 'vivaldi-gold',
    name: 'VIVALDI GOLD',
    category: 'doma',
    level: 'medio',
    age: 7,
    gender: 'Stallion',
    breed: 'Westfaliano',
    country: 'Alemania',
    height: '1.70 m',
    coat: 'Castaño',
    price: 58000,
    description: 'Hijo directo de Vitalis. Posee una mecánica de trote espectacular, con mucha libertad de espaldas. Iniciado en los cambios de pie y con una facilidad asombrosa para la reunión. Un caballo con "Look at Me" factor.',
    lineage: 'Vitalis x Florestan I',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Trote Expresivo', 'Cambios Iniciados'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },
  {
    id: 'promesa-real',
    name: 'PROMESA REAL',
    category: 'doma',
    level: 'basico',
    age: 4,
    gender: 'Stallion',
    breed: 'PRE',
    country: 'España',
    height: '1.68 m',
    coat: 'Castaño',
    price: 25000,
    description: 'Potro con orígenes inmejorables recién desbravado. Muestra un carácter excepcional y tres aires muy correctos. Ideal para amateur que quiera hacer su propio caballo desde el inicio con seguridad.',
    lineage: 'Armas Tarugo x Educado X',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Recién Desbravado', 'Carácter 10'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },
  {
    id: 'duque-magno',
    name: 'DUQUE MAGNO',
    category: 'doma',
    level: 'basico',
    age: 3,
    gender: 'Stallion',
    breed: 'Lusitano',
    country: 'Portugal',
    height: '1.66 m',
    coat: 'Castaño',
    price: 18000,
    description: 'La belleza barroca en su máxima expresión. Duque Magno tiene una elasticidad envidiable y una predisposición natural para el piaffe. Aún verde, pero con una inteligencia que hace que aprenda muy rápido.',
    lineage: 'Spartacus x Rubi AR',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Barroco Moderno', 'Mente Top'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },

  // --- SALTO ---
  {
    id: 'valkyria-z',
    name: 'VALKYRIA Z',
    category: 'salto',
    level: 'alto', 
    age: 9,
    gender: 'Mare',
    breed: 'Zangersheide',
    country: 'Bélgica',
    height: '1.70 m',
    coat: 'Castaño',
    price: 120000,
    description: 'Valkyria Z es la definición de potencia y técnica. Esta yegua de 9 años ha demostrado su valía en los circuitos internacionales (1.45m). Hija directa de Cornet Obolensky, hereda su explosividad en el despegue. Rápida pero manejable.',
    lineage: 'Cornet Obolensky x Baloubet',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Salto 1.45m', 'CSI** Experience'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },
  {
    id: 'pegasus-fly',
    name: 'PEGASUS FLY',
    category: 'salto',
    level: 'alto',
    age: 11,
    gender: 'Gelding',
    breed: 'Silla Francés',
    country: 'Francia',
    height: '1.75 m',
    coat: 'Castaño',
    price: 150000,
    description: 'Caballo de Gran Premio. Mucha experiencia en recorridos de 1.50m. Un caballo grande con un tranco inmenso que cubre el terreno sin esfuerzo. Ideal para jinete que quiera saltar ranking classes mañana mismo.',
    lineage: 'Diamant de Semilly x Voltaire',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Ranking Classes', 'Scope 1.50m'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },
  {
    id: 'quimera-sport',
    name: 'QUIMERA SPORT',
    category: 'salto',
    level: 'medio',
    age: 7,
    gender: 'Mare',
    breed: 'Holsteiner',
    country: 'España',
    height: '1.69 m',
    coat: 'Tordo Vinoso',
    price: 55000,
    description: 'Rapidez y agilidad definen a Quimera. Una yegua competitiva ideal para categorías Children o Junior. Limpia en el salto, valiente ante los rellenos y con un corazón enorme para ayudar a su jinete.',
    lineage: 'Casall x Capitol I',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Competitiva 1.30m', 'Ideal Juniors'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },
  {
    id: 'tornado-z',
    name: 'TORNADO Z',
    category: 'salto',
    level: 'medio',
    age: 8,
    gender: 'Stallion',
    breed: 'Zangersheide',
    country: 'Bélgica',
    height: '1.68 m',
    coat: 'Castaño',
    price: 48000,
    description: 'Semental aprobado con técnica perfecta de manos. Muy cuidadoso (careful), odia tocar la barra. Actualmente concursando en 1.30m con regularidad. Tiene sangre pero es muy controlable.',
    lineage: 'Taloubet Z x Indoctro',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Super Careful', 'Técnica Perfecta'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },
  {
    id: 'thunderbird-k',
    name: 'THUNDERBIRD K',
    category: 'salto',
    level: 'basico', 
    age: 5,
    gender: 'Gelding',
    breed: 'Silla Francés',
    country: 'Francia',
    height: '1.71 m',
    coat: 'Alazán',
    price: 32000,
    description: 'Joven promesa con un scope ilimitado. Saltando recorridos de 1.10m con facilidad pasmosa. Orígenes Kannan para garantizar potencia. Un caballo para construir hacia el futuro.',
    lineage: 'Kannan x Diamant de Semilly',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Scope Ilimitado', 'Ciclo Clásico'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  },
  {
    id: 'apollo-star',
    name: 'APOLLO STAR',
    category: 'salto',
    level: 'basico',
    age: 4,
    gender: 'Stallion',
    breed: 'BWP',
    country: 'Bélgica',
    height: '1.73 m',
    coat: 'Castaño',
    price: 28000,
    description: 'Recién importado. Apollo tiene un modelo impresionante y mucha fuerza. Saltando en libertad muestra reflejos felinos. Montado es valiente y va hacia adelante. Prospecto serio para profesional.',
    lineage: 'Emerald x Nabab de Reve',
    image: BROWN_HORSE_IMG,
    gallery: GALLERY_IMGS,
    features: ['Fuerza Bruta', 'Modelo Top'],
    videoVertical: 'https://www.youtube.com/embed/tgbNymZ7vqY'
  }
];